[drive]
type = drive
client_id = 173006186663-h9vshmbs46ejso663umplj8bdnh661p7.apps.googleusercontent.com
client_secret = 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
scope = drive
service_account_file = {"web":{"client_id":"173006186663-h9vshmbs46ejso663umplj8bdnh661p7.apps.googleusercontent.com","project_id":"tes-vps-362814","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"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","redirect_uris":["https://developers.google.com/oauthplayground"]}}
token = ya29.a0AVvZVsqJlHxnZV51d9b-2T2cVCN1uDRf03K0eXJbZDzVw6gHh_0HsCHadNR75S6bPh2M5wsn5d85RSunzOHPc0GwUUUgas5dHvJaRXWbq3pb5iOCxJVQfMHvryyolvFpEXMWTLgTYH5FyRgHYBXecRKvaLcpaCgYKATsSARESFQGbdwaIRfwiBkxk5FEJAHn9tPLFmw0163
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://oauth2.googleapis.com/token
list_chunk = 500
