[dr]
type = drive
{
  "access_token": "ya29.a0AVvZVsqjLyQlu_9KFc9ZppDwkVW5FTqBKQv9JZrkpP-zNTPXASIH0O4rFSUBDGgMcq4e8ioAx1CJzanvxiafXjHedPUG2HMwYPCPe5yRCfDHxa8FKYODPoEhUeMZaCDW1niF4SEj_ciyKiu5zPoT8UJrlhMBaCgYKAfASARESFQGbdwaI9VqtEglrWd37KGHAzMiajw0163", 
  "scope": "https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.file", 
  "token_type": "Bearer", 
  "expires_in": 3599, 
  "refresh_token": "1//04Zt6MdFcC46OCgYIARAAGAQSNwF-L9IrQK1QJ8LNBUcDq6UXCKWKDWAvc7LUMaIpm3d5uJSwpaA5nqI6VS1iGw2SK_JGBjpKLu8"
}
root_folder_id = 0AHM2dIhtjPQIUk9PVA
